Broke something while refactoring, but not sure what
Error:
```
finished relocating program tcc_trace function tcc_trace
Error: error opening log event array

Caused by:
    map `AYA_LOGS` not found
```